# config/routes.yaml

# Routes pour la page d'accueil

app_page:
    path: /app
    controller: App\Controller\DefaultController::app

# Routes pour se connecter et déconnecter
login:
    path: /login
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    controller: App\Controller\LoginController::logout

    # routes pour s'enregistrer
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# routes pour récupération des pierres par couleur

products_by_color:
    path: /products/{color}
    controller: App\Controller\ProductController::productsByColor